version: '3'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend: