name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    env:
      NOXSESSION: "Tests"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.1.2
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
      - name: Install Nox
        run: |
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version
      - name: Run Nox
        run: |
          nox --force-color --python=3.8
      - name: Create coverage report
        run: |
          nox --force-color --session=coverage -- xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.12
