name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    env:
      NOXSESSION: "Tests"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.1.2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
      - name: Install Nox
        run: |
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version
      - name: Compute pre-commit cache key
        id: pre-commit-cache
        shell: python
        run: |
          import hashlib
          import sys
          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = {{ '"${{ runner.os }}-{}-{}-pre-commit".format(python, digest[:8])' }}
          print("::set-output name=result::{}".format(result))
      - name: Restore pre-commit cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: |
            {{ "${{ steps.pre-commit-cache.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}" }}
          restore-keys: |
            {{ "${{ steps.pre-commit-cache.outputs.result }}-" }}
      - name: Run Nox
        run: |
          nox --force-color --python=3.8

      - name: Create coverage report
        run: |
          nox --force-color --session=coverage -- xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.12
