name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: {{ "${{ matrix.session }} ${{ matrix.python-version }} / ${{ matrix.os }}" }}
    runs-on: {{ "${{ matrix.os }}" }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.8, os: ubuntu-latest, session: "pre-commit" }
          - { python-version: 3.8, os: ubuntu-latest, session: "safety" }
          - { python-version: 3.8, os: ubuntu-latest, session: "tests" }
    env:
      NOXSESSION: {{ "${{ matrix.session }}" }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.2
      - name: Set up Python {{ "${{ matrix.python-version }}" }}
        uses: actions/setup-python@v2.1.2
        with:
          python-version: {{ "${{ matrix.python-version }}" }}
      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
      - name: Install Nox
        run: |
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version
      - name: Run Nox
        run: |
          nox --force-color --python=3.8
      - name: Create coverage report
        if: always() && matrix.session == 'tests'
        run: |
          nox --force-color --session=coverage -- xml
      - name: Upload coverage report
        if: always() && matrix.session == 'tests'
        uses: codecov/codecov-action@v1.0.12
